### ISSUE TITLE
Diagnose the stack fault in current system :

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#140]
Exception trace when reading parquet data store:

```
java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
	at org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:145)
	at org.apache.thrift.protocol.TBinaryProtocol.writeString(TBinaryProtocol.java:202)
	at org.apache.zeppelin.interpreter.thrift.RemoteInterpreterContext$RemoteInterpreterContextStandardScheme.write(RemoteInterpreterContext.java:1203)
	at org.apache.zeppelin.interpreter.thrift.RemoteInterpreterContext$RemoteInterpreterContextStandardScheme.write(RemoteInterpreterContext.java:1074)
	at org.apache.zeppelin.interpreter.thrift.Remo
```

**Comment by stvoutsin** [comment]
Had a brief look around, but wasn't able to find an obvious consistent cause of this.
Restarting the interpreter seems to have fixed the bug however. Notebooks are running fine for me after the restart. Suggestion is to close this and see if it appears again.

**Comment by stvoutsin** [comment]
Restarting the Spark interpreter:
Restarting the SparkContext only works by using the UI (Menu -> Interpreter -> Spark Interpreter -> click on restart button)
https://stackoverflow.com/questions/40550011/zeppelin-how-to-restart-sparkcontext-in-zeppelin

**Comment by Zarquan** [comment]
Yep - agree
