### ISSUE TITLE
Machine Learning notebook fails with exception "No space left on device"

### ISSUE THREAD

**Issue by stvoutsin** [wfau/aglais#277]
**Description:**
Issue seems to be that a Spark job produces intermediate data that is written to disk, and specifically /tmp/.
If a Spark job produces more data than space available, this exception is triggered, and this seems to be the case for this notebook.

**Deploy information:**
This was tested on a an automated deploy created with 3 worker nodes as described here:
https://github.com/wfau/aglais/blob/master/notes/stv/20201130-ansible-deploy-hadoop-zeppelin-02.txt

**Notebook:**
https://github.com/wfau/aglais-testing/blob/main/notebooks/Good_astrometric_solutions_via_ML_Random_Forrest_classifier.json

**Exception:**
```
Job aborted due to stage failure: Task 4438 in stage 32.0 failed 4 times, most recent failure: Lost task 4438.3 in stage 32.0 (TID 73864, worker02, executor 1): java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at org.apache.spark.storage.TimeTrackingOutputStream.write(TimeTrackingOutputStream.java:58)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at net.jpountz.lz4.LZ4BlockOutputStream.finish(LZ4BlockOutputStream.java:260)
	at net.jpountz.lz4.LZ4BlockOutputStream.close(LZ4BlockOutputStream.java:190)
	at java.io.ObjectOutputStream$BlockDataOutputStream.close(ObjectOutputStream.java:1828)
	at java.io.ObjectOutputStream.close(ObjectOutputStream.java:742)
	at org.apache.spark.serializer.JavaSerializationStream.close(JavaSerializer.scala:57)
	at org.apache.spark.storage.DiskBlockObjectWriter.commitAndGet(DiskBlockObjectWriter.scala:173)
	at org.apache.spark.util.collection.ExternalSorter.writePartitionedFile(ExternalSorter.scala:701)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:71)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Potential fix:**
Change where Spark/Hadoop write intermediate files to a Ceph share with more available disk space.

**Links:**
https://community.cloudera.com/t5/Support-Questions/spark-job-failure-with-no-space-left-on-device/td-p/197465

**Comment by stvoutsin** [comment]
Issue has been addressed by using Cinder volumes for tmp storage rather than /tmp.
