### ISSUE TITLE
Race condition triggers ConcurrentModificationException in notebook handler

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#779]
Running AglaisBenchmarker in a loop triggers a race condition in Zeppelin, resulting in the following Exception.
```
Unexpected exception: java.util.ConcurrentModificationException
    at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1633)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
    at org.apache.zeppelin.service.JobManagerService.getNoteJobInfoByUnixTime(JobManagerService.java:90)
    at org.apache.zeppelin.socket.NotebookServer.broadcastUpdateNoteJobInfo(NotebookServer.java:519)
    at org.apache.zeppelin.socket.NotebookServer.onStatusChange(NotebookServer.java:2007)
    at org.apache.zeppelin.socket.NotebookServer.onStatusChange(NotebookServer.java:105)
    at org.apache.zeppelin.scheduler.Job.setStatus(Job.java:141)
    at org.apache.zeppelin.notebook.Paragraph.setStatus(Paragraph.java:398)
    at org.apache.zeppelin.notebook.Paragraph.execute(Paragraph.java:349)
    at org.apache.zeppelin.notebook.Note.run(Note.java:873)
    at org.apache.zeppelin.service.NotebookService.runParagraph(NotebookService.java:390)
    at org.apache.zeppelin.rest.NotebookRestApi.runParagraph(NotebookRestApi.java:849)
```

This can be _mitigated (not solved)_ by increasing the delay initial delay and the delay between notebooks in AglaisBenchmarker. This may be an artefact of running the tests in a tight loop with many (~20) users. However it may still be possible to trigger this during normal use on the live server. Particularly if we are trying to support a workshop or class environment.

Test results <link>:
* Concurrent user test fails with 19 users and both the initial delay and the delay between notebooks set at the default value of 1 second.
* Concurrent user test passes with 19 users and both the initial delay and the delay between notebooks increased to 5 seconds.
<link>

We may need to do more tests to identify the minimum delay required for a given number of users.

**Comment by Zarquan** [comment]
The documentation for `HashMap` explicitly states that the implementation is **not** synchronised. 
https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html
> Note that this implementation is not synchronized. If multiple threads access a hash map concurrently, and at least one of the threads modifies the map structurally, it must be synchronized externally ...
> This is typically accomplished by synchronizing on some object that naturally encapsulates the map. If no such object exists, the map should be "wrapped" using theCollections.synchronizedMap method.

Looking at the source code for Zeppelin, we can find the location where this Exception is triggered, but it doesn't look like the stack trace that we are seeing.
https://github.com/apache/zeppelin/blame/master/zeppelin-server/src/main/java/org/apache/zeppelin/service/JobManagerService.java#L91-L99

However we can use the GitHub blame view to show us the same location before the most recent change, which is much closer to what we see in our stack trace. 
https://github.com/apache/zeppelin/blame/bef579d87f7531480052d8e9451752cae1118e36/zeppelin-server/src/main/java/org/apache/zeppelin/service/JobManagerService.java#L86-L90
 
The changes to the Zeppelin code fixes an issue concerning a memory leak.
https://issues.apache.org/jira/browse/ZEPPELIN-5559
> NoteManager never releases the note memory after a note has been read.

Looking at the GitHub PullRequest associated with this change:
https://github.com/apache/zeppelin/pull/4252
https://github.com/zlosim/zeppelin/commit/621837900005ad9a990d84435972461534881336

We can see that the change introduces a new setting
https://github.com/apache/zeppelin/blob/master/docs/setup/operation/configuration.md#zeppelin_note_cache_threshold

> `zeppelin.note.cache.threshold`
> Threshold for the number of notes in the cache before an eviction occurs.

This was merged on 3rd Feb 2022, so it might be in the latest release :-)
TODO - update to the latest release and re-test ?
