### ISSUE TITLE
Sky counts map broken

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#83]
The Sky counts map notebook fails
http://128.232.224.69:8080/#/notebook/2F2C6W3GE

    java.io.IOException: Failed to create local dir

**Comment by stvoutsin** [comment]
Which cell did you get that Exception on?
I get a different exception running the second cell :

%spark.pyspark
sql_df = spark.sql("SELECT floor(source_id / 562949953421312) AS hpx5, COUNT(*) AS n FROM gaia_source_ids GROUP BY hpx5")
print (sql_df.take(10))


Py4JJavaError: An error occurred while calling o582.collectToPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 42.0 failed 4 times, most recent failure: Lost task 2.3 in stage 42.0 (TID 99657, stv-dev-worker-4, executor 6): java.io.FileNotFoundException: /tmp/hadoop-fedora/nm-local-dir/usercache/fedora/appcache/application_1578764470640_0080/blockmgr-4717fa69-6726-40e4-b308-6c9a2b6c6c94/23/temp_shuffle_1b688861-2bf3-4823-950b-fd654c9f4fba (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
   .....

"temp_shuffle_1b688861-2bf3-4823-950b-fd654c9f4fba (No such file or directory)"

I've seen this exception before, it looks like an issue cause by tmp (cache) directory being cleared, while the job is still active or ready?

**Comment by Zarquan** [comment]
Second cell in the notebook 

    %spark.pyspark
    sql_df = spark.sql("SELECT floor(source_id / 562949953421312) AS hpx5, COUNT(*) AS n FROM gaia_source_ids GROUP BY hpx5")
    print (sql_df.take(10))

Throws a Java stack trace

    Py4JJavaError: An error occurred while calling o582.collectToPython.
    : org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 42.0 failed 4 times, most recent failure: Lost task 2.3 in stage 42.0 (TID 99657, stv-dev-worker-4, executor 6): java.io.FileNotFoundException: /tmp/hadoop-fedora/nm-local-dir/usercache/fedora/appcache/application_1578764470640_0080/blockmgr-4717fa69-6726-40e4-b308-6c9a2b6c6c94/23/temp_shuffle_1b688861-2bf3-4823-950b-fd654c9f4fba (No such file or directory)
	    at java.io.FileOutputStream.open0(Native Method)
	    at java.io.FileOutputStream.open(FileOutputStream.java:270)
	    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	    at org.apache.spark.storage.DiskBlockObjectWriter.initialize(DiskBlockObjectWriter.scala:103)
	    at org.apache.spark.storage.DiskBlockObjectWriter.open(DiskBlockObjectWriter.scala:116)
	    at org.apache.spark.storage.DiskBlockObjectWriter.write(DiskBlockObjectWriter.scala:237)
	    at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:151)
	    at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	    at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	    at org.apache.spark.scheduler.Task.run(Task.scala:123)
	    at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	    at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	    at java.lang.Thread.run(Thread.java:748)

**Comment by stvoutsin** [comment]
Might be a case of this:
https://stackoverflow.com/questions/41881343/spark-yarn-tmp-no-such-file-or-directory
I'll look into it and update with what I find

**Comment by stvoutsin** [comment]
I think this the same issue as #108 . Closing for now, if we think this is something different, or it shows up again we can re-open

**Comment by Zarquan** [comment]
Yep, agreed.
